services:
  ruoyi-admin:
    build:
      context: .
      dockerfile: Dockerfile-admin
    container_name: ruoyi-admin
    working_dir: /app
    command: sh -c "for i in {1..60}; do nc -z mysql 3306 && echo 'MySQL is ready' && break || echo 'waiting mysql...' && sleep 2; done && java -jar /app/ruoyi-admin.jar"
    ports:
      - "8080:8080"            # 后端端口
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/newblog?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - dev_network

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newblog
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d   # 初始化SQL脚本
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 20s
      retries: 20
      interval: 10s
      start_period: 120s
    networks:
      - ruoyi-network

  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5
      interval: 5s
    networks:
      - dev_network

  ruoyi-ui:
    image: node:22
    container_name: ruoyi-ui
    working_dir: /app
    volumes:
      - ./ruoyi-ui:/app
      - /app/node_modules  #避免宿主机 node_modules 覆盖容器内的
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      ruoyi-admin:
        condition: service_started
    environment:
      - DOCKER=true  # 标记当前在 Docker 环境
      - LANG=C.UTF-8
      - VITE_API_BASE_URL=http://ruoyi-admin:8080
    networks:
      - ruoyi-network
    restart: unless-stopped
volumes:
  mysql_data:

networks:
  dev_network:
    driver: bridge

volumes:
  mysql_data:
