FROM node:22-alpine

WORKDIR /app

# 复制 package.json 并安装依赖
COPY package*.json ./

# 安装依赖并清理缓存
RUN npm config set registry https://registry.npmmirror.com \
    && npm install --legacy-peer-deps --force \
    && arch=$(uname -m) \
    && if [ "$arch" = "aarch64" ]; then \
         npm install @rollup/rollup-linux-arm64-musl --save-dev; \
       fi \
    && npm cache clean --force

# 复制源代码
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host"]
